apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: triton-jes  # Replace with your namespace
type: Opaque
data: # echo -n "value" | base64
  name: <BASE64_ENCODED_NAME>
  metaurl: <BASE64_ENCODED_METAURL> # base64 of redis://[:<PASSWORD>]@<HOST>:6379[/<DB>]
  storage: <BASE64_ENCODED_STORAGE> # base64 of "s3"
  bucket: <BASE64_ENCODED_BUCKET_URL> # base64 of https://<BUCKET>.s3.<REGION>.amazonaws.com
  access-key: <BASE64_ENCODED_ACCESS_KEY>
  secret-key: <BASE64_ENCODED_SECRET_KEY>
