apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: triton-jes
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.6  # Use the desired Redis version
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: juicefs-secret  # This refers to the secret where the password is stored
              key: redis-password
        args: ["--requirepass", "$(REDIS_PASSWORD)"]  # This sets the Redis password
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: triton-jes
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379