apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-server
  template:
    metadata:
      labels:
        app: triton-server
    spec:
      # hostNetwork: true  # Use host networking if required
      containers:
      - name: triton-server
        image: quay.io/jeslynlamxy/tritonserver-with-models:latest  # Use the custom image
        ports:
        - containerPort: 8001
        resources:
          limits:
            nvidia.com/gpu: 1  # Request GPU resources
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi  # Set shared memory to 1GB
---
apiVersion: v1
kind: Service
metadata:
  name: triton-server-service
spec:
  selector:
    app: triton-server
  ports:
    - protocol: TCP
      port: 8001  # External port to access
      targetPort: 8001  # Port in the container
  type: LoadBalancer  # Expose the service externally
